### PR TITLE
Added ability to show hidden files and exit with escape

### PR DESCRIPTION
**Pull request by andreyorst**
I've also made that commands executed by script will not show in comman line history anymore

### CODE REVIEW

**Comment by TeddyDD** [comment]
Nice, thanks :)

Btw. shellcheck complains about quotes, but I'm not sure this is correct in Kakoune:

```
keys="!echo<space>../<space>&&<space>"$keys"gg"
^-- SC2027: The surrounding quotes actually unquote this. Remove or escape them.
```

**Comment by andreyorst** [comment]
>Btw. shellcheck complains about quotes, but I'm not sure this is correct in Kakoune:
>```
>keys="!echo<space>../<space>&&<space>"$keys"gg"
>^-- SC2027: The surrounding quotes actually unquote this. Remove or escape them.
>```

Well, that's `variable=string+variable+string`, so there's "text" var "text" but without spaces. It should work. Maybe we should go this instead:
```sh
keys="!echo<space>../<space>&&<space> $keys gg"
```

**Comment by TeddyDD** [comment]
yup, I'll change it.

**Comment by andreyorst** [comment]
https://github.com/TeddyDD/kakoune-edit-or-dir/blob/abdff4b62bfef43039bfc8310b10c00d6649aeb8/edit-or-dir.kak#L34

Here's the same situation. Idk why I didn't done this myself...

**Pull request merged**
